// <auto-generated />
namespace AmeCaseBookOrg.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Unlimited_DataItem_HtmlContentLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Unlimited_DataItem_HtmlContentLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201509180302102_Unlimited_DataItem_HtmlContentLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
