// <auto-generated />
namespace AmeCaseBookOrg.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_DataItem_Content_NText : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_DataItem_Content_NText));
        
        string IMigrationMetadata.Id
        {
            get { return "201509220252571_Change_DataItem_Content_NText"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
